package geraScript;

public enum Tipos {
	BIT, TINYINT, SMALLINT, INT, MEDIUMINT, BIGINT, DECIMAL, FLOAT, DOUBLE, CHAR, VARCHAR, TEXT, BINARY, VARBINARY,
	BLOB, DATE, TIME, DATETIME, TIMESTAMP, YEAR;

}
